//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Tool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_MAINTAB                     310
#define IDD_CAMERATAB                   311
#define IDD_MESHTAB                     312
#define IDD_TERRAINTAB                  313
#define IDD_ANIMATIONTAB                315
#define IDD_NAVIGATIONTAB               316
#define IDD_LIGHTTAB                    317
#define IDB_BITMAP                      318
#define IDD_EVENTCOLLIDERTAB            319
#define IDB_CONTAINER                   322
#define IDD_EFFECTTAB                   323
#define IDD_EFFECTMESHTAB               327
#define IDD_EFFECTMESH2TAB              331
#define TabControl_MainTab              1000
#define List_Scene                      1002
#define Button_CreateScene              1003
#define Edit_SceneName                  1004
#define Tree_MeshList                   1005
#define Edit_FileName                   1006
#define Edit_ModelComTag                1007
#define Button_CreateMesh               1008
#define Check_Animation                 1009
#define TabControl_PrototypeList        1010
#define List_MeshProto                  1013
#define But_MeshList_Create             1014
#define TEXT_ModelComponentText         1015
#define Edit_ModelObjectTag             1016
#define Button_EditScene                1018
#define Button_Scene_Save               1019
#define Button_Scene_Load               1020
#define Button_Scene_SaveAll            1021
#define Button_Scene_LoadAll            1022
#define Button_Scene_Delete             1023
#define Edit_Container                  1024
#define List_Container                  1025
#define Text_ContainerList              1026
#define Text_ContainerName              1027
#define Button_Container                1028
#define Tree_WorldContainer             1041
#define List_Prototype                  1042
#define Edit_PrototypeModel             1043
#define Button_InsertToContainer        1045
#define Button_DeletePrototype          1046
#define Button_SavePrototype            1047
#define Button_LoadPrototype            1048
#define Button_DeleteContainer          1052
#define Edit_Pos_X                      1053
#define Edit_Position_X                 1054
#define Edit_Position_Y                 1055
#define Edit_Position_Z                 1056
#define Spin_Position_X                 1058
#define Text_Warning                    1059
#define Spin_Position_Y                 1060
#define Spin_Position_Z                 1061
#define Edit_Scale_X                    1062
#define Spin_Scale_X                    1063
#define Edit_Scale_Y                    1064
#define Spin_Scale_Y                    1065
#define Edit_Scale_Z                    1066
#define Spin_Scale_Z                    1067
#define Edit_Rot_X                      1068
#define Spin_Rot_X                      1069
#define Edit_Rot_Y                      1070
#define Spin_Rot_Y                      1071
#define Edit_Rot_Z                      1072
#define Spin_Rot_Z                      1073
#define IDC_CAMERABUTTON1               1074
#define Edit_ObjectName                 1075
#define List_Navigation                 1076
#define Check_Picking                   1077
#define Check_AutoCreate                1078
#define Edit_Point0_X                   1079
#define Edit_Point0_Y                   1080
#define Edit_Point0_Z                   1081
#define Button_Save                     1082
#define Button_Load                     1083
#define Button_Create                   1084
#define Radio_None                      1087
#define Radio_Fall                      1088
#define Button_ForAnimationTool         1089
#define IDC_CAMERABUTTON2               1090
#define Edit_Point1_X                   1106
#define Edit_Point1_Y                   1107
#define Edit_Point1_Z                   1108
#define Edit_Point2_X                   1109
#define Edit_Point2_Y                   1110
#define Edit_Point2_Z                   1111
#define Radio_Identity                  1112
#define Radio_PivotX                    1113
#define Radio_PivotY                    1114
#define Radio_PivotZ                    1115
#define Edit_RotationDegree             1116
#define Button_Main_ChangeName          1117
#define Edit_Main_ContainerName         1118
#define IDC_TreeCtrl_Light              1120
#define Edit_Red                        1121
#define Edit_Blue                       1122
#define Edit_Green                      1123
#define Edit_Alpha                      1124
#define Text_Red                        1125
#define Text_Blue                       1126
#define Text_Green                      1127
#define Text_Alpha                      1128
#define Button_LightCreate              1129
#define Radio_Direction                 1130
#define Radio_Point                     1131
#define Radio_SpotLight                 1132
#define Edit_Light_PositionX            1133
#define Edit_Light_PositionY            1134
#define Edit_Light_PositionZ            1135
#define Edit_Light_Radius               1136
#define Text_PointLight                 1137
#define Text_DirectionLight             1138
#define Edit_Light_DirectionX           1139
#define Edit_Light_DirectionY           1140
#define Edit_Light_DirectionZ           1141
#define Edit_LightName                  1142
#define Text_LightName                  1143
#define Button_LightDelete              1145
#define Check_LightOn                   1147
#define Check_LightRender_Tool          1148
#define Text_Diffuse                    1149
#define Text_Ambient                    1150
#define Text_Specular                   1151
#define Edit_Ambient_Red                1152
#define Edit_Ambient_Blue               1153
#define Edit_Ambient_Green              1154
#define Edit_Ambient_Alpha              1155
#define Edit_Specular_Red               1156
#define Edit_Specular_Blue              1157
#define Edit_Specular_Green             1158
#define Edit_Specular_Alpha             1159
#define Button_Navi_Delete              1160
#define Edit_NavCount                   1161
#define Static_Point2                   1162
#define Static_Point1                   1163
#define Static_Point3                   1164
#define Edit_CurNavCount                1165
#define IDC_LIST1                       1166
#define IDC_BUTTON1                     1167
#define Button_LoadAllModel             1167
#define IDC_EVENTBUTTON1                1167
#define Button_Magical                  1167
#define IDC_CAMERA_TREE                 2000
#define IDC_ADD_CAMERA                  2001
#define IDC_DELETE_CAMERA               2002
#define IDC_VETRTEX_MOVE_TOGETHER       2008
#define IDC_VETRTEX_MOVE_SOLO           2009
#define IDC_AVE_SOL                     2011
#define IDC_CAMERA_POS_X                2012
#define IDC_CAMERA_POS_Y                2013
#define IDC_CAMERA_POS_Z                2014
#define IDC_SPINCTRL_CAMERA_POS_X       2015
#define IDC_SPINCTRL_CAMERA_POS_Y       2016
#define IDC_SPINCTRL_CAMERA_POS_Z       2017
#define IDC_CAMERA_SELECTION_SPEED      2018
#define IDC_SPINCTRL_SELECTION_SPEED    2019
#define IDC_CAMERA_TOTAL_SPEED          2020
#define IDC_CAMERA_TOTAL_SPEED_APPLY    2021
#define IDC_CAMERA_PLAY                 2022
#define IDC_CAMERA_PAUSE                2023
#define IDC_CAMERA_STOP                 2024
#define IDC_CAMERA_ACTION_SLIDER        2025
#define IDC_CAMERA_SAVE                 2028
#define IDC_CAMERA_LOAD                 2029
#define IDC_EFFECT_TEXTURELIST          2031
#define IDC_EFFECT_POSITION_X_EDIT      2032
#define IDC_EFFECT_POSITION_Y_EDIT      2033
#define IDC_EFFECT_POSITION_Z_EDIT      2034
#define IDC_EFFECT_SCALE_X_EDIT         2035
#define IDC_EFFECT_SCALE_Y_EDIT         2036
#define IDC_EFFECT_SCALE_Z_EDIT         2037
#define IDC_EFFECT_ROTATION_X_EDIT      2038
#define IDC_EFFECT_ROTATION_Y_EDIT      2039
#define IDC_EFFECT_ROTATION_Z_EDIT      2040
#define IDC_EFFECT_DIRECTION_X_EDIT     2041
#define IDC_EFFECT_DIRECTION_Y_EDIT     2042
#define IDC_EFFECT_DIRECTION_Z_EDIT     2043
#define IDC_EFFECT_LIFETIME_EDIT        2044
#define IDC_EFFECT_NUMBER_EDIT          2045
#define IDC_EFFECT_POSITION_X_SPIN_CTRL 2046
#define IDC_EFFECT_POSITION_Y_SPIN_CTRL 2047
#define IDC_EFFECT_POSITION_Z_SPIN_CTRL 2048
#define IDC_EFFECT_SCALE_X_SPIN_CTRL    2049
#define IDC_EFFECT_SCALE_Y_SPIN_CTRL    2050
#define IDC_EFFECT_SCALE_Z_SPIN_CTRL    2051
#define IDC_EFFECT_ROTATION_X_SPIN_CTRL 2052
#define IDC_EFFECT_ROTATION_Y_SPIN_CTRL 2053
#define IDC_EFFECT_ROTATION_Z_SPIN_CTRL 2054
#define IDC_EFFECT_DIRECTION_X_SPIN_CTRL 2055
#define IDC_EFFECT_DIRECTION_Y_SPIN_CTRL 2056
#define IDC_EFFECT_DIRECTION_Z_SPIN_CTRL 2057
#define IDC_EFFECT_LIFETIME_SPIN_CTRL   2058
#define IDC_EFFECT_NUMBER_SPIN_CTRL     2059
#define IDC_EFFECT_DENSITY_EDIT         2060
#define IDC_EFFECT_DENSITY_SPIN_CTRL    2061
#define IDC_EFFECT_DIRECTION_DENSITY_EDIT 2062
#define IDC_EFFECT_DENSITY_SPIN_CTRL2   2063
#define IDC_EFFECT_DIRECTION_DENSITY_SPIN_CTRL 2063
#define IDC_EFFECT_SPEED_EDIT           2064
#define IDC_EFFECT_SPEED_SPIN_CTRL      2065
#define IDC_EFFECT_SPEED_DENSITY_EDIT   2066
#define IDC_EFFECT_SPEED_DENSITY_SPIN_CTRL 2067
#define IDC_EFFECT_LIFETIME_DENSITY_ON_RADIO 2068
#define IDC_EFFECT_PARTICLE_LIST        2069
#define IDC_EFFECT_LIFETIME_DENSITY_OFF_RADIO 2070
#define IDC_EFFECT_WIDTH_EDIT           2071
#define IDC_EFFECT_WIDTH_SPIN_CTRL      2072
#define IDC_EFFECT_HEIGHT_EDIT          2073
#define IDC_EFFECT_HEIGHT_SPIN_CTRL     2074
#define IDC_EFFECT_SPRITE_INTERVAL_EDIT 2075
#define IDC_EFFECT_SPRITE_INTERVAL_SPIN_CTRL 2076
#define IDC_EFFECT_MESHNAME             2077
#define IDC_EFFECT_TEXTURE_NUMBER_RESULT 2077
#define IDC_EFFECT_TEXTURENAME          2078
#define IDC_EFFECT_MESHLIST             2079
#define IDC_EFFECT_TEXTURE_NUMBER_EDIT  2079
#define IDC_EFFECT_CREATE_BUTTON        2080
#define IDC_EFFECT_PLAY_BUTTON          2081
#define IDC_EFFECTMESH_CREATE_RECT_BUTTON 2082
#define IDC_EFFECT_TEXTURENAME2         2082
#define IDC_EFFECT_STOP_BUTTON          2083
#define IDC_EFFECT_OPEN_TEXTURE         2084
#define IDC_EFFECT_TEXTURENAME3         2085
#define IDC_EFFECT_DELETE_BUTTON        2086
#define IDC_EFFECT_PARTICLE_NAME_RESULT 2087
#define IDC_EFFECT_PARTICLE_NAME_EDIT   2088
#define IDC_EFFECT_TEXTURENAME4         2089
#define IDC_EFFECT_APPLY_NAME           2090
#define IDC_EFFECT_CURRENT_TEXTURE_RESULT 2091
#define IDC_EFFECT_SAVE_BUTTON          2092
#define IDC_EFFECT_LOAD_BUTTON          2093
#define IDC_EFFECT_SPEED_DENSITY_EDIT2  2094
#define IDC_EFFECT_LIFETIME_DENSITY_END_EDIT 2094
#define IDC_EFFECT_PSIZE_EDIT           2095
#define IDC_EFFECT_UPDATE_SHADER_BUTTON 2096
#define IDC_TERRAINEDIT1                3000
#define IDC_TERRAINEDIT2                3001
#define IDC_TERRAINBUTTON1              3002
#define IDC_TERRAINRADIO1               3003
#define IDC_TERRAINRADIO2               3004
#define IDC_TERRAINRADIO3               3005
#define IDC_TERRAINRADIO4               3006
#define IDC_TERRAINLIST1                3007
#define IDC_TERRAINLIST2                3008
#define IDC_TERRAINBUTTON2              3009
#define IDC_TERRAINBUTTON3              3010
#define IDC_TERRAINSTATIC               3011
#define IDC_TERRAINSTATIC2              3012
#define IDC_TERRAINSTATIC3              3013
#define IDC_TERRAINSTATIC4              3014
#define IDC_TERRAINSTATIC5              3015
#define IDC_TERRAINSTATIC6              3016
#define IDC_TERRAINSTATIC7              3017
#define IDC_TERRAINSTATIC8              3018
#define IDC_TERRAINSTATIC9              3019
#define IDC_TERRAINSLIDER1              3020
#define IDC_TERRAINSLIDER2              3021
#define IDC_TERRAINSLIDER3              3022
#define IDC_TERRAINCHECK1               3023
#define IDC_TERRAINRADIO5               3024
#define IDC_CAMERALIST1                 5000
#define IDC_CAMERALIST2                 5001
#define IDC_CAMERAEDIT1                 5003
#define IDC_CAMERAEDIT2                 5004
#define IDC_CAMERAEDIT3                 5005
#define IDC_SPIN2                       5007
#define IDC_CAMERASPIN2                 5007
#define IDC_EVENTSPIN2                  5007
#define IDC_CAMERASPIN3                 5008
#define IDC_EVENTSPIN4                  5008
#define IDC_CAMERASPIN4                 5009
#define IDC_EVENTSPIN6                  5009
#define IDC_CAMERABUTTON3               5010
#define IDC_CAMERABUTTON4               5011
#define IDC_CAMERABUTTON5               5012
#define IDC_CAMERABUTTON6               5013
#define IDC_CAMERAEDIT4                 5014
#define IDC_CAMERAEDIT5                 5016
#define IDC_CAMERAEDIT6                 5017
#define IDC_CAMERASPIN6                 5019
#define IDC_CAMERABUTTON7               5020
#define IDC_CAMERABUTTON8               5021
#define IDC_CAMERABUTTON9               5022
#define IDC_CAMERALIST3                 5023
#define IDC_CAMERAEDIT7                 5024
#define IDC_CAMERARADIO1                5025
#define IDC_CAMERARADIO2                5026
#define IDC_CAMERABUTTON10              5027
#define IDC_CAMERAEDIT8                 5028
#define IDC_CAMERAEDIT9                 5029
#define IDC_CAMERAEDIT10                5030
#define IDC_CAMERASPIN1                 5032
#define IDC_CAMERASPIN5                 5033
#define IDC_CAMERASPIN7                 5034
#define IDC_CAMERABUTTON11              5035
#define IDC_CAMERACHECK1                5119
#define IDC_EVENTEDIT1                  5120
#define IDC_EVENTEDIT2                  5121
#define IDC_EVENTEDIT3                  5122
#define IDC_EVENTLIST1                  5123
#define IDC_EVENTSTATIC                 5124
#define IDC_EVENTSTATIC2                5125
#define IDC_EVENTSTATIC3                5126
#define IDC_EVENTSPIN1                  5127
#define IDC_EVENTSPIN3                  5128
#define IDC_EVENTBUTTON2                5129
#define IDC_EVENTEDIT10                 5130
#define IDC_EVENTSPIN10                 5131
#define IDC_EVENTEDIT4                  5132
#define IDC_EVENTSTATIC4                5133
#define IDC_EVENTSTATIC5                5134
#define IDC_EVENTEDIT5                  5135
#define IDC_EVENTSPIN5                  5136
#define IDC_EVENTSTATIC6                5137
#define IDC_EVENTEDIT9                  5138
#define IDC_EVENTSPIN9                  5139
#define IDC_EVENTSTATIC7                5140
#define IDC_EVENTEDIT6                  5141
#define IDC_EVENTSTATIC8                5142
#define IDC_EVENTEDIT7                  5143
#define IDC_EVENTSPIN7                  5144
#define IDC_EVENTSTATIC9                5145
#define IDC_EVENTEDIT11                 5146
#define IDC_EVENTBUTTON3                5147
#define IDC_EVENTBUTTON4                5148
#define IDC_ANIMATIONCOMBOBOX1          6033
#define IDC_ANIMATIONLIST1              6034
#define IDC_ANIMATIONSTATIC             6035
#define IDC_ANIMATIONSTATIC2            6036
#define IDC_ANIMATIONSLIDER1            6037
#define IDC_ANIMATIONEDIT1              6038
#define IDC_ANIMATIONBUTTON1            6039
#define IDC_ANIMATIONEDIT2              6040
#define IDC_ANIMATIONSTATIC3            6041
#define IDC_ANIMATIONBUTTON2            6042
#define IDC_ANIMATIONSTATIC4            6043
#define IDC_ANIMATIONEDIT3              6044
#define IDC_ANIMATIONSPIN1              6045
#define IDC_ANIMATIONSTATIC5            6046
#define IDC_ANIMATIONBUTTON3            6047
#define IDC_ANIMATIONBUTTON4            6048
#define IDC_ANIMATIONSPIN2              6049
#define IDC_ANIMATIONBUTTON10           6050
#define IDC_ANIMATIONBUTTON5            6051
#define IDC_ANIMATIONLIST2              6052
#define IDC_ANIMATIONSTATIC6            6053
#define IDC_ANIMATIONCHECK1             6054
#define IDC_ANIMATIONBUTTON6            6055
#define IDC_ANIMATIONEDIT5              6056
#define IDC_ANIMATIONEDIT6              6057
#define IDC_ANIMATIONEDIT7              6058
#define IDC_ANIMATIONSTATIC7            6059
#define IDC_ANIMATIONSTATIC8            6060
#define IDC_ANIMATIONBUTTON7            6061
#define IDC_ANIMATIONEDIT8              6062
#define IDC_ANIMATIONSTATIC10           6063
#define IDC_ANIMATIONEDIT10             6064
#define IDC_ANIMATIONSTATIC19           6065
#define IDC_ANIMATIONCHECK2             6066
#define IDC_ANMAITONSTATIC11            6067
#define IDC_ANIMATIONEDIT11             6068
#define IDC_ANIMATIONSPIN3              6069
#define IDC_BUTTON2                     6070
#define IDC_ANIMATIONSTATIC12           6071
#define EDIT_ROOT_KEY_INDEX             6072
#define IDC_ANIMATIONSTATIC15           6073
#define IDC_ANIMATIONSPIN4              6074
#define EDIT_BONE_POS_X                 6076
#define IDC_ANIMATIONEDIT18             6077
#define IDC_ANIMATIONEDIT19             6078
#define IDC_ANIMATIONSTATIC17           6079
#define IDC_ANIMATIONEDIT20             6080
#define IDC_ANIMATIONSTATIC18           6081
#define IDC_ANIMATIONSTATIC21           6082
#define IDC_ANIMATIONBUTTON9            6083
#define IDC_ANIMATIONSTATIC101          6084
#define IDC_ANIMATIONEDIT21             6085
#define IDC_ANIMATIONSTATIC100          6086
#define IDC_ANIMATIONSPIN5              6087
#define IDC_ANIMATIONSTATIC102          6088
#define IDC_ANIMATIONSPIN6              6089
#define IDC_ANIMATIONSTATIC103          6090
#define IDC_ANIMATIONSPIN7              6091
#define IDC_ANIMATIONEDIT100            6092
#define IDC_ANIMATIONEDIT101            6093
#define IDC_EFFECTMESH_POSITION_X_RESULT 7001
#define IDC_EFFECTMESH_POSITION_X_EDIT  7002
#define IDC_EFFECTMESH_POSITION_Y_RESULT 7003
#define IDC_EFFECTMESH_POSITION_Y_EDIT  7004
#define IDC_EFFECTMESH_POSITION_Z_RESULT 7005
#define IDC_EFFECTMESH_POSITION_Z_EDIT  7006
#define IDC_EFFECTMESH_POSITION_X_SPINCTRL 7007
#define IDC_EFFECTMESH_POSITION_Y_SPINCTRL 7008
#define IDC_EFFECTMESH_POSITION_Z_SPINCTRL 7009
#define IDC_EFFECTMESH_SCALE_X_RESULT   7010
#define IDC_EFFECTMESH_SCALE_X_EDIT     7011
#define IDC_EFFECTMESH_SCALE_Y_RESULT   7012
#define IDC_EFFECTMESH_SCALE_Y_EDIT     7013
#define IDC_EFFECTMESH_SCALE_Z_RESULT   7014
#define IDC_EFFECTMESH_SCALE_Z_EDIT     7015
#define IDC_EFFECTMESH_SCALE_X_SPINCTRL 7016
#define IDC_EFFECTMESH_SCALE_Y_SPINCTRL 7017
#define IDC_EFFECTMESH_SCALE_Z_SPINCTRL 7018
#define IDC_EFFECTMESH_ROTATION_X_RESULT 7019
#define IDC_EFFECTMESH_ROTATION_X_EDIT  7020
#define IDC_EFFECTMESH_ROTATION_Y_RESULT 7021
#define IDC_EFFECTMESH_ROTATION_Y_EDIT  7022
#define IDC_EFFECTMESH_ROTATION_Z_RESULT 7023
#define IDC_EFFECTMESH_ROTATION_Z_EDIT  7024
#define IDC_EFFECTMESH_ROTATION_X_SPINCTRL 7025
#define IDC_EFFECTMESH_ROTATION_Y_SPINCTRL 7026
#define IDC_EFFECTMESH_ROTATION_Z_SPINCTRL 7027
#define IDC_EFFECTMESH_MESH_NAME        7028
#define IDC_EFFECTMESH_GROUP_NAME_RESULT 7029
#define IDC_EFFECTMESH_GROUP_NAME_EDIT  7030
#define IDC_EFFECTMESH_CURRENT_EFFECT_NAME_RESULT 7031
#define IDC_EFFECTMESH_CURRENT_EFFET_NAME_EDIT 7032
#define IDC_EFFECTMESH_CURRENT_EFFECT_NAME_EDIT 7032
#define IDC_EFFECTMESH_CREATE_IMAGELESS_MESH_BUTTON 7033
#define IDC_EFFECTMESH_CREATE_IMAGELESS_IMAGELESS_MESH_BUTTON 7033
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_RESULT 7034
#define IDC_EFFECTMESH_DEFAULT_TEXTURE_CHECK 7035
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_CHECK 7035
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_RESULT 7036
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_CHECK 7037
#define IDC_EFFECTMESH_TEXTURE_MASK_RESULT 7038
#define IDC_EFFECTMESH_TEXTURE_MASK_CHECK 7039
#define IDC_EFFECTMESH_CREATE_TIME_RESULT 7040
#define IDC_EFFECTMESH_CREATE_TIME_EDIT 7041
#define IDC_EFFECTMESH_DEATH_TIME_RESULT 7042
#define IDC_EFFECTMESH_DEATH_TIME_EDIT  7043
#define IDC_EFFECTMESH_CREATE_DEATH_REPEAT 7044
#define IDC_EFFECTMESH_PATTERN_POSITION_X_RESULT 7045
#define IDC_EFFECTMESH_PATTERN_POSITION_X_EDIT 7046
#define IDC_EFFECTMESH_PATTERN_POSITION_Y_RESULT 7047
#define IDC_EFFECTMESH_PATTERN_POSITION_Y_EDIT 7048
#define IDC_EFFECTMESH_PATTERN_POSITION_Z_RESULT 7049
#define IDC_EFFECTMESH_PATTERN_POSITION_Z_EDIT 7050
#define IDC_EFFECTMESH_PATTERN_POSITION_X_SPIN_CTRL 7051
#define IDC_EFFECTMESH_PATTERN_POSITION_Y_SPIN_CTRL 7052
#define IDC_EFFECTMESH_PATTERN_POSITION_Z_SPIN_CTRL 7053
#define IDC_EFFECTMESH_CREATE_IMAGELESSMESH_BUTTON22 7054
#define IDC_EFFECTMESH_CREATE_MESH_BUTTON 7054
#define IDC_EFFECTMESH_SCROLLBAR        7055
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_NUMBER_RESULT 7055
#define IDC_EFFECTMESH_PLAY_BUTTON      7056
#define IDC_EFFECTMESH_STOP_BUTTON      7057
#define IDC_EFFECTMESH_SAVE_BUTTON      7058
#define IDC_EFFECTMESH_LOAD_BUTTON      7059
#define IDC_EFFECTMESH_EFFECTMESH_LIST  7060
#define IDC_EFFECTMESH_APPLY_GROUP_NAME_BUTTON 7061
#define IDC_EFFECTMESH_APPLY_CURRENT_EFFECT_NAME_BUTTON 7062
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_SPRITE_REPEAT_CHECK 7063
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_NUMBER_EDIT 7064
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_NUMBER_RESULT 7065
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_NUMBER_EDIT 7066
#define IDC_EFFECTMESH_TEXTURE_MASK_NUMBER_RESULT 7067
#define IDC_EFFECTMESH_TEXTURE_MASK_NUMBER_EDIT 7068
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_SPRITE_REPEAT_CHECK 7069
#define IDC_EFFECTMESH_TEXTURE_MASK_SPRITE_REPEAT_CHECK 7070
#define IDC_EFFECTMESH_LOAD_BUTTON2     7071
#define IDC_EFFECTMESH_LOAD_WITH_PARTICLE_BUTTON 7071
#define IDC_EFFECTMESH_PATTERN_POSITION_START_TIME_RESULT 7072
#define IDC_EFFECTMESH_PATTERN_POSITION_START_TIME_EDIT 7073
#define IDC_EFFECTMESH_PATTERN_POSITION_END_TIME_RESULT 7074
#define IDC_EFFECTMESH_PATTERN_POSITION_END_TIME_EDIT 7075
#define IDC_EFFECTMESH_PATTERN_POSITION_REPEAT_CHECK 7076
#define IDC_EFFECTMESH_PATTERN_POSITION_SELECT_ALL_CHECK 7077
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_INTERVAL_RESULT 7081
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_INTERVAL_EDIT 7082
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_INTERVAL_RESULT 7083
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_INTERVAL_EDIT 7084
#define IDC_EFFECTMESH_TEXTURE_MASK_INTERVAL_RESULT 7085
#define IDC_EFFECTMESH_TEXTURE_MASK_INTERVAL_EDIT 7086
#define IDC_EFFECTMESH_PATTERN_POSITION_PROJECTILE_CHECK 7087
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_LENGTH_MIN_RESULT 7089
#define IDC_EFFECTMESH_PATTERN_POSITION_PROJECTILE_RANDOM_LENGTH_MIN_RESULT 7089
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_LENGTH_MIN_EDIT 7090
#define IDC_EFFECTMESH_PATTERN_ROTATION_X_RESULT 7093
#define IDC_EFFECTMESH_PATTERN_ROTATION_X_EDIT 7094
#define IDC_EFFECTMESH_PATTERN_ROTATION_Y_RESULT 7095
#define IDC_EFFECTMESH_PATTERN_ROTATION_Y_EDIT 7096
#define IDC_EFFECTMESH_PATTERN_ROTATION_Z_RESULT 7097
#define IDC_EFFECTMESH_PATTERN_ROTATION_Z_EDIT 7098
#define IDC_EFFECTMESH_PATTERN_ROTATION_X_SPIN_CTRL 7099
#define IDC_EFFECTMESH_PATTERN_ROTATION_Y_SPIN_CTRL 7100
#define IDC_EFFECTMESH_PATTERN_ROTATION_Z_SPIN_CTRL 7101
#define IDC_EFFECTMESH_PATTERN_ROTATION_START_TIME_RESULT 7102
#define IDC_EFFECTMESH_PATTERN_ROTATION_START_TIME_EDIT 7103
#define IDC_EFFECTMESH_PATTERN_ROTATION_END_TIME_RESULT 7104
#define IDC_EFFECTMESH_PATTERN_ROTATION_END_TIME_EDIT 7105
#define IDC_EFFECTMESH_PATTERN_ROTATION_REPEAT_CHECK 7106
#define IDC_EFFECTMESH_PATTERN_ROTATION_SELECT_ALL_CHECK 7107
#define IDC_EFFECTMESH_PATTERN_SCALE_X_RESULT 7108
#define IDC_EFFECTMESH_PATTERN_SCALE_Y_RESULT 7109
#define IDC_EFFECTMESH_PATTERN_SCALE_X_EDIT 7110
#define IDC_EFFECTMESH_PATTERN_SCALE_Z_RESULT 7111
#define IDC_EFFECTMESH_PATTERN_SCALE_Y_EDIT 7112
#define IDC_EFFECTMESH_PATTERN_SCALE_Z_EDIT 7113
#define IDC_EFFECTMESH_PATTERN_SCALE_X_SPIN_CTRL 7114
#define IDC_EFFECTMESH_PATTERN_SCALE_Y_SPIN_CTRL 7115
#define IDC_EFFECTMESH_PATTERN_SCALE_START_TIME_RESULT 7116
#define IDC_EFFECTMESH_PATTERN_SCALE_START_TIME_EDIT 7117
#define IDC_EFFECTMESH_PATTERN_SCALE_END_TIME_RESULT 7118
#define IDC_EFFECTMESH_PATTERN_SCALE_END_TIME_EDIT 7119
#define IDC_EFFECTMESH_PATTERN_SCALE_REPEAT_CHECK 7120
#define IDC_EFFECTMESH_PATTERN_SCALE_SELECT_ALL_CHECK 7121
#define IDC_EFFECTMESH_PATTERN_SCALE_Z_SPIN_CTRL 7122
#define IDC_EFFECTMESH_FADE_IN_DEGREE_RESULT 7123
#define IDC_EFFECTMESH_FADE_IN_DEGREE_EDIT 7124
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_LENGTH_MAX_RESULT 7125
#define IDC_EFFECTMESH_PATTERN_POSITION_PROJECTILE_RANDOM_LENGTH_MAX_RESULT 7125
#define IDC_EFFECTMESH_FADE_IN_START_TIME_RESULT 7126
#define IDC_EFFECTMESH_FADE_IN_START_TIME_EDIT 7127
#define IDC_EFFECTMESH_FADE_IN_END_TIME_RESULT 7128
#define IDC_EFFECTMESH_FADE_IN_END_TIME_EDIT 7129
#define IDC_EFFECTMESH_FADE_IN_CHECK    7130
#define IDC_EFFECTMESH_FADE_IN_CURRENT_TIME_RESULT 7131
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_LENGTH_MAX_EDIT 7132
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_LENGTH_RESULT 7133
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_ANGLE_MIN_RESULT 7134
#define IDC_EFFECTMESH_PATTERN_POSITION_PROJECTILE_RANDOM_ANGLE_MIN_RESULT 7134
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_ANGLE_MIN_EDIT 7135
#define IDC_EFFECTMESH_PATTERN_ANGLE_RANDOM_ANGLE_MAX_RESULT 7136
#define IDC_EFFECTMESH_PATTERN_POSITION_PROJECTILE_RANDOM_ANGLE_MAX_RESULT 7136
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_ANGLE_MAX_RESULT 7136
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_ANGLE_MAX_EDIT 7137
#define IDC_EFFECTMESH_PATTERN_POSITION_RANDOM_ANGLE_RESULT 7138
#define IDC_EFFECTMESH_FADE_OUT_DEGREE_RESULT 7141
#define IDC_EFFECTMESH_FADE_OUT_DEGREE_EDIT 7142
#define IDC_EFFECTMESH_FADE_OUT_START_TIME_RESULT 7144
#define IDC_EFFECTMESH_FADE_OUT_START_TIME_EDIT 7145
#define IDC_EFFECTMESH_FADE_OUT_END_TIME_RESULT 7146
#define IDC_EFFECTMESH_FADE_OUT_END_TIME_EDIT 7147
#define IDC_EFFECTMESH_FADE_OUT_CHECK   7148
#define IDC_EFFECTMESH_FADE_OUT_CURRENT_TIME_RESULT 7149
#define IDC_EFFECTMESH_UV_SPRITE_START_TIME_RESULT 7158
#define IDC_EFFECTMESH_UV_SPRITE_START_TIME_EDIT 7159
#define IDC_EFFECTMESH_UV_SPRITE_END_TIME_RESULT 7160
#define IDC_EFFECTMESH_UV_SPRITE_END_TIME_EDIT 7161
#define IDC_EFFECTMESH_UV_SPRITE_CHECK  7162
#define IDC_EFFECTMESH_UV_SPRITE_CURRENT_TIME_RESULT 7165
#define IDC_EFFECTMESH_UV_SPRITE_WIDTH_RESULT 7166
#define IDC_EFFECTMESH_UV_SPRITE_WIDTH_EDIT 7167
#define IDC_EFFECTMESH_UV_SPRITE_HEIGHT_RESULT 7168
#define IDC_EFFECTMESH_UV_SPRITE_HEIGHT_EDIT 7169
#define IDC_EFFECTMESH_UV_SPRITE_NUMBER_RESULT 7170
#define IDC_EFFECTMESH_UV_SPRITE_NUMBER_EDIT 7171
#define IDC_EFFECTMESH_UV_ANIMATION_START_TIME_RESULT 7172
#define IDC_EFFECTMESH_UV_ANIMATION_START_TIME_EDIT 7173
#define IDC_EFFECTMESH_UV_ANIMATION_END_TIME_RESULT 7174
#define IDC_EFFECTMESH_UV_ANIMATION_END_TIME_EDIT 7175
#define IDC_EFFECTMESH_UV_ANIMATION_CHECK 7176
#define IDC_EFFECTMESH_UV_ANIMATION_CURRENT_TIME_RESULT 7177
#define IDC_EFFECTMESH_UV_ANIMATION_X_RESULT 7178
#define IDC_EFFECTMESH_UV_ANIMATION_X_EDIT 7179
#define IDC_EFFECTMESH_UV_ANIMATION_Y_RESULT 7180
#define IDC_EFFECTMESH_UV_ANIMATION_Y_EDIT 7181
#define IDC_EFFECTMESH_DUPLICATE_BUTTON 7182
#define IDC_EFFECTMESH_DELETE_BUTTON    7183
#define IDC_EFFECTMESH_TEXTURE_DEFAULT_BROWSE_BUTTON 7184
#define IDC_EFFECTMESH_TEXTURE_ALPHAONE_BROWSE_BUTTON 7185
#define IDC_EFFECTMESH_TEXTURE_MASK_BROWSE_BUTTON 7186
#define IDC_MESHEFFECT_PATTERN_POSITION_PROJECTILE_RANDOM_LENGTH_ANGLE_CACULATE_BUTTON 7187
#define IDC_EFFECTMESH2_SHADER_LIST     7188
#define IDC_EFFECTMESH2_ADDED_SHADER_LIST 7189
#define IDC_MESHEFFECT2_ADD_SHADER_BUTTON 7190
#define IDC_EFFECTMESH2_DELETE_SHADER_BUTTON 7191
#define IDC_EFFECTMESH_UPDATE_SHADER_BUTTON 7191
#define IDC_EFFECT_APPLY_TEXTURE_BUTTON 7192
#define IDC_EFFECT_REPEAT               7193
#define IDC_EFFECT_MULTI_TEXTURE_INTERVAL_EDIT 7194
#define IDC_EFFECT_FADE_IN_CHECK        7195
#define IDC_EFFECT_FADE_IN_EDIT         7196
#define IDC_EFFECT_FADE_OUT_CHECK       7197
#define IDC_EFFECT_FADE_OUT_EDIT        7198
#define IDC_EFFECT_MULTI_TEXTURE_SPRITE_REPEAT 7199
#define IDC_EFFECT_FADE_OUT_END_EDIT    7200

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        335
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         5149
#define _APS_NEXT_SYMED_VALUE           320
#endif
#endif
