#pragma once
#ifndef __CLIENT_GAME_OBJECT_KEY_H__
#define __CLIENT_GAME_OBJECT_KEY_H__
namespace Client {

	// Game Object Prototype Tag
#define PROTO_KEY_TERRAIN				TEXT("Prototype_Terrain")
#define PROTO_KEY_TOOLCAMERA			TEXT("Prototype_ToolCamera")
#define PROTO_KEY_TOOLOBJECT			TEXT("Prototype_ToolObject")
#define PROTO_KEY_MODEL_PLAYER			TEXT("Prototype_Model_Player")
#define PROTO_KEY_MODEL_9S				TEXT("Prototype_Model_9S")
#define PROTO_KEY_MODEL_IRON9S			TEXT("Prototype_Model_Iron9S")
#define PROTO_KEY_MODEL_KATANA			TEXT("Prototype_Model_Katana")
#define PROTO_KEY_MODEL_LONGKATANA		TEXT("Prototype_Model_LongKatana")
#define PROTO_KEY_MODEL_SPEAR			TEXT("Prototype_Model_Spear")
#define PROTO_KEY_MODEL_GAUNTLET		TEXT("Prototype_Model_Gauntlet")
#define PROTO_KEY_MODEL_IRONGAUNTLET	TEXT("Prototype_Model_IronGauntlet")
#define PROTO_KEY_MODEL_POD				TEXT("Prototype_Model_Pod")
#define PROTO_KEY_MODEL_POD9S			TEXT("Prototype_Model_Pod9S")
#define PROTO_KEY_MODEL_BEAUVOIR		TEXT("Prototype_Model_Beauvoir")
#define PROTO_KEY_MODEL_ZHUANGZI		TEXT("Prototype_Model_Zhuangzi")
#define PROTO_KEY_MODEL_ENGELS			TEXT("Prototype_Model_Engels")
#define PROTO_KEY_MODEL_CROSSANDROID	TEXT("Prototype_Model_CrossAndroid")
#define PROTO_KEY_COLLIDER_SPHERE		TEXT("Prototype_Collider_SPHERE")
#define PROTO_KEY_MOUSE					TEXT("Prototype_Mouse")
#define PROTO_KEY_CAMERA				TEXT("Prototype_Camera")
#define PROTO_KEY_IRONFIST_CAMERA		TEXT("Prototype_IronFist_Camera")
#define PROTO_KEY_BUILDING				TEXT("Prototype_Building")
#define PROTO_KEY_PLAYER				TEXT("Prototype_Player")
#define PROTO_KEY_KATANA				TEXT("Katana")
#define PROTO_KEY_BEAUVOIR_SKIRT		TEXT("Skirt")
#define PROTO_KEY_BEAUVOIR_HAIR			TEXT("Hair")
#define PROTO_KEY_LONGKATANA			TEXT("LongKatana")
#define PROTO_KEY_SPEAR					TEXT("Spear")
#define PROTO_KEY_GAUNTLET				TEXT("Gauntlet")
#define PROTO_KEY_IRONGAUNTLET			TEXT("IronGauntlet")
#define PROTO_KEY_POD					TEXT("Pod")
#define PROTO_KEY_POD9S					TEXT("Pod9S")
#define PROTO_KEY_9S					TEXT("Prototype_9S")
#define PROTO_KEY_IRON9S				TEXT("Prototype_Iron9S")
#define PROTO_KEY_IRONHUMANOID_SMALL	TEXT("Prototype_IronHumanoid_Small")
#define PROTO_KEY_IRONFIST_BACKGROUND   TEXT("Prototype_IronFist_BackGround")
#define PROTO_KEY_HUMANOID_SMALL		TEXT("Prototype_Humanoid")
#define PROTO_KEY_HUMANOID_BIG			TEXT("Prototype_Humanoid_Big")
#define PROTO_KEY_TANK					TEXT("Prototype_Tank")
#define PROTO_KEY_DRAGOON				TEXT("Prototype_Humanoid_Dragoon")
#define PROTO_KEY_BEAUVOIR				TEXT("Prototype_Beauvoir")
#define PROTO_KEY_ZHUANGZI				TEXT("Prototype_Zhuangzi")
#define PROTO_KEY_CROSSANDROID			TEXT("Prototype_CrossAndroid")
#define PROTO_KEY_WHOLERANGE			TEXT("Prototype_WholeRange")
#define PROTO_KEY_ENGELS				TEXT("Prototype_Engels")
#define PROTO_KEY_ENGELS_HITPART		TEXT("Prototype_Engels_HitPart")
#define PROTO_KEY_ZHUANGZIBRIDGE		TEXT("ZhuangziBridge")
#define PROTO_KEY_ZHUANGZIDOOR			TEXT("ZhuangziDoor")
#define PROTO_KEY_BEAUVOIR_CURATIN		TEXT("Prototype_Curtain")

#define PROTO_KEY_MODEL_IRON_HUMANOID_SMALL TEXT("Prototype_Model_IronHumanoid_Small")
#define PROTO_KEY_VENDING_MACHINE		TEXT("Prototype_VendingMachine")
}

#endif // !__CLIENT_GAME_OBJECT_KEY_H__