#pragma once
#ifndef __CLIENT_COMPONENT_KEY_H__
#define __CLIENT_COMPONENT_KEY_H__

namespace Client {

// Component - Have GameObject 
#define COM_KEY_RECT					TEXT("Com_VIBuffer_Rect")
#define COM_KEY_TERRAIN					TEXT("Com_VIBuffer_Terrain")
#define COM_KEY_CUBE					TEXT("Com_VIBuffer_Cube")
#define COM_KEY_MODEL					TEXT("Com_Model")
#define COM_KEY_TEXTURE					TEXT("Com_Texture")
#define COM_KEY_SUBJECT					TEXT("Com_Subject")
#define COM_KEY_COLLIDER				TEXT("Com_Collider")
#define COM_KEY_RENDERER				TEXT("Com_Renderer")
#define COM_KEY_TRANSFORM				TEXT("Com_Transform")
#define COM_KEY_FILTER					TEXT("Com_Filter")
#define COM_KEY_BRUSH					TEXT("Com_Brush")
#define COM_KEY_NAVIGATION				TEXT("Com_Navigation")
#define	COM_KEY_OBB						TEXT("Com_OBB")
#define	COM_KEY_AABB					TEXT("Com_AABB")
#define COM_KEY_SPHERE					TEXT("Com_SPHERE")
#define COM_KEY_HITBOX					TEXT("Com_HitBox")
#define COM_KEY_ATTACKBOX				TEXT("Com_AttackBox")
#define COM_KEY_MIDDLEPOINT				TEXT("Com_MiddlePoint")
#define COM_KEY_INVENTORY				TEXT("Com_Inventory")
#define COM_KEY_SWAPBOX					TEXT("Com_SwapBox")

// Component Prototype Key
#define PROTO_KEY_RENDERER				TEXT("Prototype_Renderer")
#define PROTO_KEY_TRANSFORM				TEXT("Prototype_Transform")
#define PROTO_KEY_VIBUFFER_RECT			TEXT("Prototype_Rect")
#define PROTO_KEY_VIBUFFER_CUBE			TEXT("Prototyep_VIBuffer_Cube")
#define PROTO_KEY_COLLIDER_AABB			TEXT("Prototype_Collider_AABB")
#define PROTO_KEY_COLLIDER_OBB			TEXT("Prototype_Collider_OBB")
#define PROTO_KEY_COLLIDER_SPHERE		TEXT("Prototype_Collider_SPHERE")
#define PROTO_KEY_VIBUFFER_TERRAIN		TEXT("Prototype_VIBuffer_Terrain")
#define PROTO_KEY_TEXTURE_TERRAIN		TEXT("Prototype_Texture_Terrain")
#define PROTO_KEY_TEXTURE_FILTER0		TEXT("Prototype_Texture_Filter0")
#define PROTO_KEY_TEXTURE_BRUSH0		TEXT("Prototype_Texture_Brush0")
#define PROTO_KEY_TEXTURE_ATLAS			TEXT("Prototype_Texture_Atlas")
#define PROTO_KEY_TEXTURE_BREAK			TEXT("Prototype_Texture_Break")
#define PROTO_KEY_TEXTURE_BURNINGFIELD	TEXT("Prototype_Texture_BurningField")
#define PROTO_KEY_TEXTURE_CRACK0		TEXT("Prototype_Texture_Crack0")
#define PROTO_KEY_TEXTURE_CRACK1		TEXT("Prototype_Texture_Crack1")
#define PROTO_KEY_TEXTURE_SPIN			TEXT("Prototype_Texture_Spin")
#define PROTO_KEY_TEXTURE_BOOM			TEXT("Prototype_Texture_Boom")
#define PROTO_KEY_TEXTURE_ARCH			TEXT("Prototype_Texture_Arch")
#define PROTO_KEY_TEXTURE_FOGRING		TEXT("Prototype_Fog_Ring")
#define PROTO_KEY_NAVIGATION_DEFAULT	TEXT("Prototype_Navigation_Test")
#define PROTO_KEY_NAVIGATION_IRONFIST	TEXT("Prototype_Navigation_IronFist")
#define PROTO_KEY_NAVIGATION_AMUSE		TEXT("Prototype_Navigation_AmusementPark")
#define PROTO_KEY_NAVIGATION_COASTER	TEXT("Prototype_Navigation_Coaster")
#define PROTO_KEY_NAVIGATION_OPERA		TEXT("Prototype_Navigation_OperaBackStage")
#define PROTO_KEY_NAVIGATION_ZHUANGZI	TEXT("Prototype_Navigation_ZhuangziStage")
#define PROTO_KEY_NAVIGATION_ENGELS		TEXT("Prototype_Navigation_ROBOTGENERAL")
#define PROTO_KEY_COLLIDER_AABB			TEXT("Prototype_Collider_AABB")
#define PROTO_KEY_COLLIDER_OBB			TEXT("Prototype_Collider_OBB")
#define PROTO_KEY_COLLIDER_SPHERE		TEXT("Prototype_Collider_SPHERE")
#define PROTO_KEY_LOGO_SCREEN			TEXT("Prototype_Logo_Screen")
#define PROTO_KEY_LOGO_TITLE			TEXT("Prototype_Logo_Title")
#define PROTO_KEY_LOGO_GEAR				TEXT("Prototype_Logo_Gear")
#define PROTO_KEY_LOGO_ANYKEY			TEXT("Prototype_Logo_AnyKey")
#define PROTO_KEY_LOGO_COPYRIGHT		TEXT("Prototype_Logo_CopyRight")
#define PROTO_KEY_LOADING_SCREEN		TEXT("Prototype_Loading_Screen")
#define PROTO_KEY_LOADING_PERCENT		TEXT("Prototype_Loading_Percent")
#define PROTO_KEY_LOADING_EMIL			TEXT("Prototype_Loading_Emil")
#define PROTO_KEY_MODEL_SKY				TEXT("Prototype_Model_Sky")
#define PROTO_KEY_MODEL_SKY_MORNING		TEXT("Prototype_Model_Sky_Morning")
#define PROTO_KEY_MODEL_SKY_AFTERNOON	TEXT("Prototype_Model_Sky_Afternoon")
#define PROTO_KEY_INVENTORY				TEXT("Prototype_Inventory")
#define PROTO_KEY_MODEL_ZHUANGZIBRIDGE	TEXT("Prototype_Model_ZhuangziBridge")
#define PROTO_KEY_MODEL_ZHUANGZIDOOR	TEXT("Prototype_Model_ZhuangziDoor")
#define PROTO_KEY_MODEL_CURTAIN			TEXT("Prototype_Model_Curtain")

#define PROTO_KEY_MODEL_IRONFIST_BACKGROUND TEXT("Prototype_Model_IronFist_Background")

#define PROTO_KEY_MODEL_VENDING_MACHINE	TEXT("Prototype_Model_VendingMachine")
#define PROTO_KEY_MODEL_DEAD_NIER		TEXT("Prototype_Model_DeadNier")
}

#endif // !__CLIENT_COMPONENT_KEY_H__