#pragma once
#ifndef __CLIENT_ITEMCODE_H__
#define __CLIENT_ITEMCODE_H__

#define ITEMCODE_MONEY							0	// Normal
#define ITEMCODE_CRISTAL						3	// Rare
#define ITEMCODE_CASH							5	// Unique

#define	ITEMCODE_EXPENDABLES_RECOVERY_SMALL		10	// Normal
#define	ITEMCODE_EXPENDABLES_RECOVERY_MIDDLE	13	// Rare
#define	ITEMCODE_EXPENDABLES_RECOVERY_LARGE		15	// Unique
#define ITEMCODE_EXPENDABLES_RECOVERY_EXLARGE	17	// Legendary
#define ITEMCODE_EXPENDABLES_RECOVERY_ALL		19	// Epic

#define ITEMCODE_RESOURCES_CHUNK				20	// Normal
#define ITEMCODE_RESOURCES_COPPER				21	// Normal
#define ITEMCODE_RESOURCES_STEEL				22	// Normal
#define ITEMCODE_RESOURCES_AMBER				23	// Rare
#define ITEMCODE_RESOURCES_SILVER				24	// Rare
#define ITEMCODE_RESOURCES_MOLDABYTE			25	// Unique
#define ITEMCODE_RESOURCES_METEORITE			26	// Unique
#define ITEMCODE_RESOURCES_PEARL				27	// Legendary
#define ITEMCODE_RESOURCES_TITAN				28	// Legendary
#define ITEMCODE_RESOURCES_SM_ALLOY				29	// Epic

#define ITEMCODE_SPECIALS_DOOR_KEY				30	// Normal

#define ITEMCODE_EQUIPMENT_WHITE_COVENANT		49	// Epic
#define ITEMCODE_EQUIPMENT_WHITE_CONTRACT		59	// Epic
#define ITEMCODE_EQUIPMENT_40TH_SPEAR			69	// Epic
#define ITEMCODE_EQUIPMENT_40TH_KNUCKLE			79	// Epic

#define ITEMCODE_ENFORCECHIP_SKILL_OS			80	// Normal
#define ITEMCODE_ENFORCECHIP_SKILL_MACHINEGUN	81	// Normal
#define ITEMCODE_ENFORCECHIP_SKILL_HANG			82	// Normal
#define	ITEMCODE_ENFORCECHIP_SKILL_LASER		83	// Rare
#define	ITEMCODE_ENFORCECHIP_SKILL_LIGHT		84	// Rare
#define	ITEMCODE_ENFORCECHIP_MASTERY_SHORTSWORD	85	// Unique
#define	ITEMCODE_ENFORCECHIP_MASTERY_LONGSWORD	86	// Unique
#define	ITEMCODE_ENFORCECHIP_MASTERY_SPEAR		87	// Legendary
#define	ITEMCODE_ENFORCECHIP_MASTERY_GAUNTLET	88	// Legendary

#endif